# Generated by Django 2.2.7 on 2019-12-02 07:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('ID', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('filename', models.CharField(default='', max_length=252)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Login.User', verbose_name='Image Owner')),
            ],
            options={
                'db_table': 'Image List',
            },
        ),
    ]
