# Generated by Django 2.2.7 on 2019-12-15 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0002_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='images',
            name='ID',
        ),
        migrations.AlterField(
            model_name='images',
            name='filename',
            field=models.CharField(max_length=128, primary_key=True, serialize=False),
        ),
    ]
